#!/bin/bash
until ping -c 3 baidu.com ; do sleep 2 ; done ; echo succeed
if [[ $? == 0 ]];then
	if [[ -e /usr/share/AdGuardHome ]] && [[ -e /etc/init.d/AdGuardHome ]]; then
		chmod -R +x /usr/share/AdGuardHome /etc/init.d/AdGuardHome
		until bash /usr/share/AdGuardHome/update_core.sh ; do sleep 3 ; done ; echo succeed
		sleep 91
		rm -rf /etc/adgup
		exit 0
	fi
else
	exit 0
fi
