name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 更新插件源
      shell: bash
      run: |
        cd $HOME_PATH
        source ${BUILD_PATH}/common.sh && Diy_menu3
 
    - name: 加载自定义设置
      shell: bash
      run: |
        cd $HOME_PATH
        source ${BUILD_PATH}/common.sh && Diy_menu4
        
    - name: 安装插件源
      shell: bash
      run: |
        cd $HOME_PATH
        source ${BUILD_PATH}/common.sh && Diy_menu5
    
    - name: SSH远程连接（make menuconfig）
      if: env.SSH_ACTION == 'true'
      uses: danshui-git/debugger-action@main

    - name: 生成"${{ matrix.target }}"配置文件
      shell: bash
      run: |
        cd $HOME_PATH
        source ${BUILD_PATH}/common.sh && Diy_menu6
        
branding:
  icon: "terminal"
  color: "gray-dark"
