name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 发送[在线更新固件]至云端1
      id: yunduan
      if: env.UPDATE_FIRMWARE_ONLINE == 'true'
      uses: ncipollo/release-action@v1
      with:
        name: AutoUpdate
        tag: ${{ env.UPDATE_TAG }}
        token: ${{ env.REPO_TOKEN }}
        allowUpdates: true
        body: ${{ env.Tongzhi_Date }}
        artifacts: "${{ env.BIN_PATH }}/*"
        
    - name: 发送[在线更新固件]至云端2
      if: steps.yunduan.outcome == 'success' && env.UPDATE_FIRMWARE_ONLINE == 'true'
      shell: bash
      run: |
        mkdir -p Github_Api
        cd Github_Api
        curl -H "Authorization: Bearer ${{ env.REPO_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.UPDATE_TAG }} -o zzz_api
        if ! grep -q "browser_download_url" zzz_api; then
          curl -H "Authorization: Bearer ${REPO_TOKEN}" https://api.github.com/repos/${GIT_REPOSITORY}/releases/tags/${UPDATE_TAG} > zzz_api
        fi
        
    - name: 发送[在线更新固件]至云端3
      if: steps.yunduan.outcome == 'success' && env.UPDATE_FIRMWARE_ONLINE == 'true'
      uses: ncipollo/release-action@v1
      with:
        name: AutoUpdate-${{ env.TARGET_BOARD }}
        tag: ${{ env.UPDATE_TAG }}
        token: ${{ env.REPO_TOKEN }}
        artifacts: "Github_Api/*"
        allowUpdates: true
        body: ${{ env.Tongzhi_Date }}

    - name: 发送[在线更新固件]至云端4
      if: steps.yunduan.outcome == 'success' && env.UPDATE_FIRMWARE_ONLINE == 'true'
      shell: bash
      run: |
        cd $HOME_PATH
        echo "YUNDUAN_MESSAGE=、发送云端" >> ${GITHUB_ENV}
branding:
  icon: "terminal"
  color: "gray-dark"
