name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 运行杂项
      shell: bash
      run: |
        cd $HOME_PATH
        echo "运行自定义1文件"
        $DIY_P1_SH
        ./scripts/feeds update -a > /dev/null 2>&1
        [ -d "$BUILD_PATCHES" ] && find "$BUILD_PATCHES" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 --forward --no-backup-if-mismatch"
        [ -d "$BUILD_DIY" ] && cp -Rf $BUILD_DIY/* $HOME_PATH
        [ -d "$BUILD_FILES" ] && cp -Rf $BUILD_FILES $HOME_PATH
        rm -rf $HOME_PATH/files/README
        mv $CONFIG_FILE $HOME_PATH/.config
        ./scripts/feeds install -a > /dev/null 2>&1
        
    - name: 安装feeds
      shell: bash
      run: |
        cd $HOME_PATH
        echo "安装feeds"
        ./scripts/feeds install -a

    - name: 运行自定义2文件
      shell: bash
      run: |
        cd $HOME_PATH
        echo "运行自定义2文件"
        $DIY_P2_SH

    - name: 提取编译机型名称
      shell: bash
      run: |
        cd $HOME_PATH
        echo "提取编译机型名称"
        make defconfig > /dev/null 2>&1
        TARGET_BOARD="$(awk -F '[="]+' '/TARGET_BOARD/{print $2}' .config)"
        TARGET_SUBTARGET="$(awk -F '[="]+' '/TARGET_SUBTARGET/{print $2}' .config)"
        TARGET_PROFILE_DG="$(awk -F '[="]+' '/TARGET_PROFILE/{print $2}' .config)"
        if [[ -n "$(grep -Eo 'CONFIG_TARGET.*x86.*64.*=y' .config)" ]]; then
          TARGET_PROFILE="x86-64"
        elif [[ -n "$(grep -Eo 'CONFIG_TARGET.*x86.*=y' .config)" ]]; then
          TARGET_PROFILE="x86-32"
        elif [[ -n "$(grep -Eo 'CONFIG_TARGET.*DEVICE.*phicomm.*n1=y' .config)" ]]; then
          TARGET_PROFILE="phicomm_n1"
        elif [[ -n "$(grep -Eo 'CONFIG_TARGET.*armsr.*armv8.*=y' .config)" ]]; then
          TARGET_PROFILE="aarch_64"
        elif [[ -n "$(grep -Eo 'CONFIG_TARGET.*armvirt.*64.*=y' .config)" ]]; then
          TARGET_PROFILE="aarch_64"
        elif [[ -n "$(grep -Eo 'CONFIG_TARGET.*DEVICE.*=y' .config)" ]]; then
          TARGET_PROFILE="$(grep -Eo "CONFIG_TARGET.*DEVICE.*=y" .config | sed -r 's/.*DEVICE_(.*)=y/\1/')"
        else
          TARGET_PROFILE="${TARGET_PROFILE_DG}"
        fi
        echo "DEVICE_NAME=${TARGET_PROFILE}" >> ${GITHUB_ENV}
        echo "BIN_TARGETS=${HOME_PATH}/bin_firmware" >> ${GITHUB_ENV}
        echo "FIRMWARE=${HOME_PATH}/bin/targets/${TARGET_BOARD}/${TARGET_SUBTARGET}" >> ${GITHUB_ENV}

    - name: 公告
      if: env.CACHEWRTBUILD_SWITCH == 'true'
      shell: bash
      run: |
        cd $HOME_PATH
        echo "缓存加速"
        
    - name: 缓存加速
      if: env.CACHEWRTBUILD_SWITCH == 'true'
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        mixkey: "${{ env.DEVICE_NAME }}"
        prefix: ${{ github.workspace }}/openwrt

    - name: 下载软件源
      shell: bash
      run: |
        cd $HOME_PATH
        echo "下载软件源"
        make download -j8
        
branding:
  icon: "terminal"
  color: "gray-dark"
