name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 更新插件源
      shell: bash
      run: |
        cd $HOME_PATH
        source $COMMON_SH && Diy_menu3
 
    - name: 加载自定义设置
      shell: bash
      run: |
        cd $HOME_PATH
        ${BUILD_PARTSH}
        source $COMMON_SH && Diy_menu4
        echo "${Customized_Information}"
        
    - name: 安装插件源
      shell: bash
      run: |
        cd $HOME_PATH
        source $COMMON_SH && Diy_menu5
        echo "${Customized_Information}"
    
    - name: SSH远程连接（make menuconfig）
      if: env.SSH_ACTION == 'true'
      uses: danshui-git/debugger-action@main

    - name: 生成配置文件
      shell: bash
      run: |
        cd $HOME_PATH
        source $COMMON_SH && Diy_menu6
        echo "Firmware_Date=$(date +%Y-%m%d-%H%M)" >> ${GITHUB_ENV}
        echo "SendMessage=true" >> ${GITHUB_ENV}

    - name: 上传配置文件在 Github Artifacts
      if: env.SHANG_CHUAN == 'true'
      uses: actions/upload-artifact@main
      with:
        name: .config_${{ env.SOURCE }}_${{ env.LUCI_EDITION }}_${{ env.TARGET_PROFILE }}_${{ env.Firmware_Date }}
        path: openwrt/build_logo/config.txt
branding:
  icon: "terminal"
  color: "gray-dark"
