name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 下载源码后进行源码微调和增加插件源
      shell: bash
      run: |
        cd $HOME_PATH
        bash $COMMON_SH Diy_menu

    - name: SSH远程连接（make menuconfig）
      if: env.SSH_ACTION == 'true'
      uses: danshui-git/debugger-action@main

    - name: 生成配置文件和提取机型
      shell: bash
      run: |
        cd $HOME_PATH
        bash $COMMON_SH Diy_menu2

    - name: 机型为aarch_64的时,改变是远程更新为打包设置
      shell: bash
      run: |
        cd $HOME_PATH
        if [[ "${TARGET_BOARD}" =~ (armvirt|armsr) ]]; then
          echo "PACKAGING_FIRMWARE=${UPDATE_FIRMWARE_ONLINE}" >> ${GITHUB_ENV}
          echo "UPDATE_FIRMWARE_ONLINE=false" >> ${GITHUB_ENV}
        fi

    - name: 远程更新,如果UPDATE_FIRMWARE_ONLINE == 'true'则运行
      if: env.UPDATE_FIRMWARE_ONLINE == 'true'
      shell: bash
      run: |
        cd $HOME_PATH
        source ${UPGRADE_SH} && Diy_Part2
  
    - name: 判断插件有否冲突减少编译错误
      shell: bash
      run: |
        cd $HOME_PATH
        bash $COMMON_SH Diy_menu3
        echo "Firmware_Date=$(date +%Y-%m%d-%H%M)" >> ${GITHUB_ENV}
        echo "SendMessage=true" >> ${GITHUB_ENV}

    - name: 上传配置文件在 Github Artifacts
      if: env.SHANG_CHUAN == 'true'
      uses: actions/upload-artifact@main
      with:
        name: .config_${{ env.SOURCE }}_${{ env.LUCI_EDITION }}_${{ env.TARGET_PROFILE }}_${{ env.Firmware_Date }}
        path: openwrt/build_logo/config.txt
branding:
  icon: "terminal"
  color: "gray-dark"
