name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 触发启动开始编译
      id: gitpush
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        tmpdir="$(mktemp -d)" && UPLOAD="$GITHUB_WORKSPACE/${tmpdir#*.}"
        git clone -b ${GIT_REFNAME} https://user:${REPO_TOKEN}@github.com/${GIT_REPOSITORY}.git $UPLOAD
        [[ -d "$UPLOAD/build" ]] && rm -rf $UPLOAD/build
        cp -Rf ${HOME_PATH}/build_logo/config.txt $MYCONFIG_FILE
        cp -Rf $OPERATES_PATH $UPLOAD/build
        [[ -d "$UPLOAD/build/common" ]] && rm -rf $UPLOAD/build/common
        cp -Rf $GITHUB_WORKSPACE/.github/workflows/* $UPLOAD/.github/workflows
        mkdir -p "$UPLOAD/build/${FOLDER_NAME}/relevance"
        echo "${SOURCE}-${REPO_BRANCH}-${CONFIG_FILE}-$(date +%Y年%m月%d号%H时%M分%S秒)" > $UPLOAD/build/${FOLDER_NAME}/relevance/start
        cp -Rf $COMPILE_PATH/relevance/settings.ini $UPLOAD/build/${FOLDER_NAME}/relevance/settings.ini
        YML_PATH="$UPLOAD/.github/workflows/compile.yml"
        TARGET1="$(grep 'target: \[' "${YML_PATH}" |sed 's/^[ ]*//g' |grep -v '^#' |sed 's/\[/\\&/' |sed 's/\]/\\&/')"
        TARGET2="target: \\[${FOLDER_NAME}\\]"
        PATHS1="$(grep -Eo "\- '.*'" "${YML_PATH}" |sed 's/^[ ]*//g' |grep -v "^#" |awk 'NR==1')"
        PATHS2="- 'build/${FOLDER_NAME}/relevance/start'"
        if [[ -n "${PATHS1}" ]] && [[ -n "${TARGET1}" ]]; then
          sed -i "s?${PATHS1}?${PATHS2}?g" "${YML_PATH}"
          sed -i "s?${TARGET1}?${TARGET2}?g" "${YML_PATH}"
        else
          echo "获取变量失败,请勿胡乱修改compile.yml文件"
          exit 1
        fi
        chmod -R +x $UPLOAD
        cd $UPLOAD
        git add .
        git commit -m "编译-${FOLDER_NAME}-${LUCI_EDITION}-${TARGET_PROFILE}固件"
        git push --force "https://${REPO_TOKEN}@github.com/${GIT_REPOSITORY}" HEAD:${GIT_REFNAME}
        if [[ $? -ne 0 ]]; then
          echo -e "\033[31m 触发编译${FOLDER_NAME}-${LUCI_EDITION}-${TARGET_PROFILE}失败 \033[0m"
        else
          echo -e "\033[33m 触发编译${FOLDER_NAME}-${LUCI_EDITION}-${TARGET_PROFILE}成功 \033[0m"
        fi

    - name: 信息通知的时间
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        echo "TZ_Message=$(date +%Y年%m月%d号%H时%M分)" >> ${GITHUB_ENV}
        
    - name: Telegram或pushplus信息通知
      if: env.PUSH_PLUS_TOKEN && env.INFORMATION_NOTICE == 'PUSH' && steps.gitpush.outcome == 'success' || env.TELEGRAM_BOT_TOKEN && env.INFORMATION_NOTICE == 'TG' && steps.gitpush.outcome == 'success'
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        if [[ "${{ env.INFORMATION_NOTICE }}" == "TG" ]]; then
          curl -s -X POST -H "Content-Type: application/json" -d '{"chat_id":"${{env.TELEGRAM_CHAT_ID}}", "text":"触发启动${{env.SOURCE}}-${{env.LUCI_EDITION}}，编译${{env.TARGET_PROFILE}}固件，请耐心等待...... 😋，(${{env.WAREHOUSE_MAN}}-#${{env.RUN_NUMBER}})，${{env.TZ_Message}}💐"}' https://api.telegram.org/bot${{env.TELEGRAM_BOT_TOKEN}}/sendMessage
        fi
        if [[ "${{ env.INFORMATION_NOTICE }}" == "PUSH" ]]; then
          curl -s -X POST -H "Content-Type: application/json" -d '{"token":"${{env.PUSH_PLUS_TOKEN}}","title":"触发启动${{env.SOURCE}}-${{env.LUCI_EDITION}}","content":"编译${{env.TARGET_PROFILE}}固件，请耐心等待...... 😋，(${{env.WAREHOUSE_MAN}}-#${{env.RUN_NUMBER}})，${{env.TZ_Message}}💐"}' https://www.pushplus.plus/send
        fi
branding:
  icon: "terminal"
  color: "gray-dark"
