name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 触发启动开始编译
      id: gitpush
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        git -b ${GIT_REFNAME} clone https://user:${REPO_TOKEN}@github.com/${GIT_REPOSITORY}.git UPLOAD
        rm -rf UPLOAD/*
        cp -Rf ${HOME_PATH}/build_logo/config.txt ${CONFIG_FILE}
        cp -Rf $OPERATES_PATH/* UPLOAD
        cp -Rf .github/workflows/* UPLOAD/.github/workflows
        mkdir -p "UPLOAD/build/${FOLDER_NAME}/relevance"
        cp -Rf $OPERATES_PATH/relevance/settings.ini UPLOAD/build/${FOLDER_NAME}/relevance/settings.ini
        YML_PATH="UPLOAD/.github/workflows/compile.yml"
        TARGET1="$(grep 'target: \[' "${YML_PATH}" |sed 's/^[ ]*//g' |grep -v '^#' |sed 's/\[/\\&/' |sed 's/\]/\\&/')"
        TARGET2="target: \\[${FOLDER_NAME}\\]"
        PATHS1="$(grep -Eo "\- '.*'" "${YML_PATH}" |sed 's/^[ ]*//g' |grep -v "^#" |awk 'NR==1')"
        PATHS2="- 'build/${FOLDER_NAME}/relevance/start'"
        if [[ -n "${PATHS1}" ]] && [[ -n "${TARGET1}" ]]; then
          sed -i "s?${PATHS1}?${PATHS2}?g" "${YML_PATH}"
          sed -i "s?${TARGET1}?${TARGET2}?g" "${YML_PATH}"
        else
          echo "获取变量失败,请勿胡乱修改compile.yml文件"
          exit 1
        fi
        echo "${SOURCE}-${REPO_BRANCH}-${CONFIG_FILE}-$(date +%Y年%m月%d号%H时%M分%S秒)" > UPLOAD/build/${FOLDER_NAME}/relevance/start

        cd UPLOAD
        BRANCH_HEAD="$(git rev-parse --abbrev-ref HEAD)"
        git add .
        git commit -m "编译-${FOLDER_NAME}-${LUCI_EDITION}-${TARGET_PROFILE}固件"
        git push --force "https://${REPO_TOKEN}@github.com/${GIT_REPOSITORY}" HEAD:${GIT_REFNAME}









        
        source ${BUILD_PATH}/common.sh && build_openwrt
        echo "TZ_Message=$(date +%Y年%m月%d号%H时%M分)" >> ${GITHUB_ENV}
        
    - name: Telegram或pushplus信息通知
      if: env.PUSH_PLUS_TOKEN && env.INFORMATION_NOTICE == 'PUSH' && steps.gitpush.outcome == 'success' || env.TELEGRAM_BOT_TOKEN && env.INFORMATION_NOTICE == 'TG' && steps.gitpush.outcome == 'success'
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        if [[ "${{ env.INFORMATION_NOTICE }}" == "TG" ]]; then
          curl -s -X POST -H "Content-Type: application/json" -d '{"chat_id":"${{env.TELEGRAM_CHAT_ID}}", "text":"触发启动${{env.SOURCE}}-${{env.LUCI_EDITION}}，编译${{env.TARGET_PROFILE}}固件，请耐心等待...... 😋，(${{env.WAREHOUSE_MAN}}-#${{env.RUN_NUMBER}})，${{env.TZ_Message}}💐"}' https://api.telegram.org/bot${{env.TELEGRAM_BOT_TOKEN}}/sendMessage
        fi
        if [[ "${{ env.INFORMATION_NOTICE }}" == "PUSH" ]]; then
          curl -s -X POST -H "Content-Type: application/json" -d '{"token":"${{env.PUSH_PLUS_TOKEN}}","title":"触发启动${{env.SOURCE}}-${{env.LUCI_EDITION}}","content":"编译${{env.TARGET_PROFILE}}固件，请耐心等待...... 😋，(${{env.WAREHOUSE_MAN}}-#${{env.RUN_NUMBER}})，${{env.TZ_Message}}💐"}' https://www.pushplus.plus/send
        fi
branding:
  icon: "terminal"
  color: "gray-dark"
