name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 密匙token
      shell: bash
      run: |
        echo "GIT_REFNAME=${{ github.ref_name }}" >> ${GITHUB_ENV}
      
    - name: 密匙检测
      shell: bash
      run: |
        cd "$GITHUB_WORKSPACE"
        if [[ -z "${{ env.REPO_TOKEN }}" ]]; then
          echo -e "\033[31m 您没有设置仓库密匙，请按教程设置好密匙再来 \033[0m\n"
          echo -e "\033[32m REPO_TOKEN密匙制作教程：https://git.io/jm.md \033[0m\n"
          exit 1
        fi
        rm -rf mishi
        git clone --depth=1 -b "${{ github.ref_name }}" https://user:${{ env.REPO_TOKEN }}@github.com/${{github.repository}}.git mishi
        cd mishi
        ls -a

        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
branding:
  icon: "terminal"
  color: "gray-dark"
