name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 密匙检测（密匙为空则退出）
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        if [[ -n "${{ env.REPO_TOKEN }}" ]]; then
          curl -s -H "Authorization: Bearer ${{ env.REPO_TOKEN }}" https://api.github.com/repos/281677160/common/releases/tags/API > mishi
          if [[ `grep -c "Bad credentials" mishi` -ge '1' ]]; then
            echo -e "\033[31m 您的密匙不正确或已过期，请按教程设置好密匙再来 \033[0m"
            echo -e "\033[31m REPO_TOKEN密匙制作教程：https://git.io/jm.md \033[0m"
            exit 1
          fi
        elif [[ -z "${{ env.REPO_TOKEN }}" ]]; then
          echo -e "\033[31m 您没有设置仓库密匙，请按教程设置好密匙再来 \033[0m"
          echo -e "\033[31m REPO_TOKEN密匙制作教程：https://git.io/jm.md \033[0m"
          exit 1
        fi
        
branding:
  icon: "terminal"
  color: "gray-dark"
