name: 'Use common script to package Armvirt as OpenWrt'
author: 'common'
description: 'Package Armvirt as OpenWrt. Support Amlogic s9xxx tv box.'
inputs:
  mode:
    description: 'Choose script.'
    required: false
    default: 'common'
  armvirt64_path:
    description: 'Choose armvirt64 file path.'
    required: false
    default: 'openwrt/bin/targets/*/*/*rootfs.tar.gz'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        echo "armvirt64_path"
branding:
  icon: 'terminal'
  color: 'gray-dark'
