name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: ä¸Šä¼ å›ºä»¶åœ¨ github Artifacts
      if: env.UPLOAD_FIRMWARE == 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE }}-${{ env.LUCI_EDITION }}-${{ env.TARGET_PROFILE }}-firmware-${{ env.Firmware_Date }}
        path: ${{ env.FIRMWARE_PATH }}
    
    - name: å‘å¸ƒå›ºä»¶
      if: env.UPLOAD_RELEASE == 'true' && env.ING_FIRMWAR == 'true'
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.SOURCE }}-${{ env.PROMPT_TING }}
        tag: a${{ env.date }}
        token: ${{ secrets.REPO_TOKEN }}
        allowUpdates: true
        body: ${{ env.Tongzhi_Date }}
        artifacts: "${{ env.FIRMWARE_PATH }}/*"
        
    - name: Telegramæˆ–pushplusä¿¡æ¯é€šçŸ¥
      if: steps.compile.outcome == 'success' && env.PUSH_PLUS_TOKEN && env.INFORMATION_NOTICE == 'PUSH' || steps.compile.outcome == 'success' && env.TELEGRAM_BOT_TOKEN && env.INFORMATION_NOTICE == 'TG'
      run: |
        if [[ "${{ env.INFORMATION_NOTICE }}" == "TG" ]]; then
          curl -s -X POST -H "Content-Type: application/json" -d '{"chat_id":"${{ secrets.TELEGRAM_CHAT_ID }}", "text":"æˆ‘äº²çˆ±çš„âœ¨ä¸»äººâœ¨ï¼šæ‚¨ä½¿ç”¨ã€${{matrix.target}}ã€‘æ–‡ä»¶å¤¹ç¼–è¯‘ã€${REPO_BRANCH}åˆ†æ”¯çš„${{env.TARGET_PROFILE}}ã€‘å›ºä»¶é¡ºåˆ©ç¼–è¯‘å®Œæˆäº†âœŒï¸ðŸ’¯ðŸ’(${{env.WAREHOUSE_MAN}}ä»“åº“çš„#${{env.RUN_NUMBER}}å·)ï¼($(date +%Yå¹´%mæœˆ%då·%Hæ—¶%Måˆ†))"}' https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
        fi
        if [[ "${{ env.INFORMATION_NOTICE }}" == "PUSH" ]]; then
          curl -s -X POST -H "Content-Type: application/json" -d '{"token":"${{ secrets.PUSH_PLUS_TOKEN }}","title":"${{ env.SOURCE }}-${{ env.TARGET_PROFILE }}ç¼–è¯‘æˆåŠŸ","content":"æˆ‘äº²çˆ±çš„âœ¨ä¸»äººâœ¨ï¼šæ‚¨ä½¿ç”¨ã€${{matrix.target}}ã€‘æ–‡ä»¶å¤¹ç¼–è¯‘ã€${REPO_BRANCH}åˆ†æ”¯çš„${{env.TARGET_PROFILE}}ã€‘å›ºä»¶é¡ºåˆ©ç¼–è¯‘å®Œæˆäº†âœŒï¸ðŸ’¯ðŸ’(${{env.WAREHOUSE_MAN}}ä»“åº“çš„#${{env.RUN_NUMBER}}å·)ï¼($(date +%Yå¹´%mæœˆ%då·%Hæ—¶%Måˆ†))"}' https://www.pushplus.plus/send
        fi

    - name: å‘é€[åœ¨çº¿æ›´æ–°å›ºä»¶]è‡³äº‘ç«¯4
      if: steps.yunduan.outcome == 'success' && env.UPDATE_FIRMWARE_ONLINE == 'true'
      shell: bash
      run: |
        echo "YUNDUAN_MESSAGE=ã€å‘é€äº‘ç«¯" >> ${GITHUB_ENV}
branding:
  icon: "terminal"
  color: "gray-dark"
