name: 'My Composite Action'
description: 'Combines multiple steps'
runs:
  using: "composite"
  steps:
    - name: 检查rootfs.tar.gz是否存在
      shell: bash
      run: |
        cd $HOME_PATH
        find $FIRMWARE_PATH -type f -name "*.tar.gz" -size -1M -delete
        if [[ ! "${TARGET_PROFILE}" == "aarch_64" ]]; then
          echo -e "\033[31m 非aarch64指定打包系列 \033[0m"
          echo "PACKAGING_FIRMWARE=false" >> ${GITHUB_ENV}
        elif [[ -n "$(find $FIRMWARE_PATH -maxdepth 1 -name '*rootfs.tar.gz' -print -quit)" ]]; then
          mkdir -p "${HOME_PATH}/targz"
          cp -Rf ${FIRMWARE_PATH}/*rootfs.tar.gz ${HOME_PATH}/targz/${SOURCE}-armvirt-64-default-rootfs.tar.gz
          echo "PACKAGING_FIRMWARE=true" >> ${GITHUB_ENV}
        else
          echo -e "\033[31m 没发现armvirt-64-default-rootfs.tar.gz包存在 \033[0m"
          echo "PACKAGING_FIRMWARE=false" >> ${GITHUB_ENV}
        fi
        
    - name: 将rootfs.tar.gz发布releases的targz
      if: env.PACKAGING_FIRMWARE == 'true'
      uses: ncipollo/release-action@v1
      with:
        name: rootfs.tar.gz
        tag: targz
        token: ${{ env.REPO_TOKEN }}
        allowUpdates: true
        replacesArtifacts: true
        artifacts: openwrt/targz/*rootfs.tar.gz

    - name: 打包aarch64系列固件
      if: env.PACKAGING_FIRMWARE == 'true'
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/targz/*rootfs.tar.gz
        openwrt_board: ${{ env.amlogic_model }}
        openwrt_kernel: ${{ env.amlogic_kernel }}
        auto_kernel: ${{ env.auto_kernel }}
        kernel_repo: ${{ env.kernel_repo }}
        kernel_usage: ${{ env.kernel_usage }}
        openwrt_size: ${{ env.openwrt_size }}
        builder_name: ${{ env.builder_name }}

    - name: 打包后的固件放回原位
      if: env.PACKAGING_FIRMWARE == 'true'
      shell: bash
      run: |
        cd $HOME_PATH
        if [[ -d "${PACKAGED_OUTPUTPATH}" ]]; then
          cp -Rf $PACKAGED_OUTPUTPATH/* $FIRMWARE_PATH
        fi
        rm -rf $PACKAGED_OUTPUTPATH
branding:
  icon: "terminal"
  color: "gray-dark"
