#!/bin/sh

network_test() {
    # 初始化网络状态标志
    network_up=0

    # 遍历 DNS 服务器列表
    for dns in "www.baidu.com" "www.google.com" "223.5.5.5" "8.8.8.8"; do
        # 尝试向每个 DNS 服务器发送 ping 请求
        ping -c 3 "$dns"
        if [ $? -eq 0 ]; then
            network_up=1
            break
        fi
    done

    # 如果所有 DNS 服务器都无法响应，则认为网络不可用
    if [ $network_up -eq 0 ]; then
        /etc/init.d/network restart
        /etc/init.d/dnsmasq restart
        grep -q "network_check" "/etc/crontabs/root" && sed -i '/network_check/d' /etc/crontabs/root
        /etc/init.d/cron restart
        echo "$(date): 网络连接失败，已重启网络服务" > /var/log/network_check.log
        echo "网络连接失败，已重启网络服务和openwrt系统"
        reboot -f
    else
        grep -q "network_check" "/etc/crontabs/root" && sed -i '/network_check/d' /etc/crontabs/root
        /etc/init.d/cron restart
        echo "$(date): 网络连接正常" > /var/log/network_check.log
        echo "网络连接正常"
    fi
}

network_test
