#!/bin/sh

rm -rf /tmp/baidu.html > /dev/null 2>&1
curl --connect-timeout 9 -o /tmp/baidu.html -s -w %{time_namelookup}: https://www.baidu.com > /dev/null 2>&1
if [[ -f /tmp/baidu.html ]] && [[ `grep -c "百度一下" /tmp/baidu.html` -ge '1' ]]; then
  rm -rf /tmp/baidu.html
else
  wangluo1='1'
  rm -rf /tmp/baidu.html
fi

rm -rf /tmp/taobao.html > /dev/null 2>&1
curl --connect-timeout 9 -o /tmp/taobao.html -s -w %{time_namelookup}: https://www.taobao.com > /dev/null 2>&1
if [[ -f /tmp/taobao.html ]] && [[ `grep -c "淘宝" /tmp/taobao.html` -ge '1' ]]; then
  rm -rf /tmp/taobao.html
else
  wangluo2='2'
  rm -rf /tmp/taobao.html
fi

rm -rf /tmp/google.html > /dev/null 2>&1
curl --connect-timeout 9 -o /tmp/google.html -s -w %{time_namelookup}: https://www.google.com > /dev/null 2>&1
if [[ -f /tmp/google.html ]] && [[ `grep -c "google" /tmp/google.html` -ge '1' ]]; then
  rm -rf /tmp/google.html
else
  wangluo3='3'
  rm -rf /tmp/google.html
fi

if [[ "${wangluo1}" == "1" ]] && [[ "${wangluo2}" == "2" ]] && [[ "${wangluo3}" == "3" ]]; then
  echo "[没检测到网络，重启系统于$(date "+%Y年%m月%d日%H时%M分%S秒")]" >> /tmp/networkdetection.log
  /etc/init.d/uhttpd restart
  /etc/init.d/network restart
  /etc/init.d/dnsmasq restart
  /etc/init.d/system restart
  sed -i '/networkdetection/d' /etc/crontabs/root >/dev/null 2>&1
  /etc/init.d/cron restart
  rm -rf /etc/networkdetection
  reboot -f
else
  echo "[$(date "+%Y年%m月%d日%H时%M分%S秒")-网络正常]" >> /tmp/networkdetection.log
  sed -i '/networkdetection/d' /etc/crontabs/root >/dev/null 2>&1
  /etc/init.d/cron restart
  rm -rf /etc/networkdetection
fi

exit 0
