#!/bin/sh

# 打印函数
function TIME() {
    case $1 in
       z)
          echo -e "\033[0;31m$2\033[0m\n";;
       g)
          echo -e "\033[0;32m$2\033[0m\n";;
       b)
          echo -e "\033[0;36m$2\033[0m\n";;
       y)
          echo -e "\033[0;33m$2\033[0m\n";;
       *)
          echo -e "\033[0;0m$2\033[0m\n";;
    esac
}

judge() {
  if [ $? -eq 0 ]; then
    TIME b "执行 $1 完成,系统正在重启中..."
    reboot -f
  else
    TIME z "执行 $1 失败"
    exit 1
  fi
}

# 修改后台IP并清空密码
modify_ip_and_clear_password() {
  clear
  echo
  TIME b "请输入您想要更改成的后台IP (格式: x.x.x.x)"
  while :; do
    read -p "IP地址： " ip
    if [ -n "$ip" ] && echo "$ip" | grep -Eoq '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'; then
      uci set network.lan.ipaddr="$ip"
      uci commit network
      TIME g "您的IP已修改为：$ip"
      clear_password
      judge "修改IP和清空密码"
      break
    else
      TIME z "请输入正确的IP地址格式"
    fi
  done
}

# 清空密码
clear_password() {
  clear
  echo
  while :; do
    read -p "是否清空密码？[Y/n]： " choice
    case $choice in
      [Yy])
        grep -q "admin:" "/etc/shadow" && passwd -d admin
        passwd -d root
        judge "清空密码"
        break
        ;;
      [Nn])
        TIME z "退出操作"
        exit 0
        ;;
      *)
        TIME z "请输入正确的选择 [Y/n]"
        ;;
    esac
  done
}

# 重启系统
reboot_system() {
  clear
  echo
  while :; do
    read -p "是否重启系统？[Y/n]： " choice
    case $choice in
      [Yy])
        TIME g "系统正在重启，请稍后登录后台"
        reboot -f
        break
        ;;
      [Nn])
        TIME z "退出操作"
        exit 0
        ;;
      *)
        TIME z "请输入正确的选择 [Y/n]"
        ;;
    esac
  done
}

# 恢复出厂设置
restore_factory_settings() {
  clear
  echo
  TIME z "是否恢复出厂设置？按[Y/y]执行，按[N/n]退出"
  firstboot
}

# 在线更新固件或转换固件
upgrade_firmware() {
  TIME b "正在执行在线更新或转换固件操作..."
  AutoUpgrade -u
  exit 0
}

# 菜单函数
show_menu() {
  clear
  echo
  TIME b "请选择执行命令编码"
  TIME y "1. 修改后台IP和清空密码"
  TIME y "2. 清空密码"
  TIME y "3. 重启系统"
  TIME y "4. 恢复出厂设置"
  TIME y "5. 退出程序"

  while :; do
    read -p "请输入数字： " choice
    case $choice in
      1) modify_ip_and_clear_password ;;
      2) clear_password ;;
      3) reboot_system ;;
      4) restore_factory_settings ;;
      5) TIME z "您选择了退出程序" && exit 0 ;;
      *) TIME z "请输入正确的数字编号" ;;
    esac
  done
}

# 带有固件更新选项的菜单函数
show_menu_with_upgrade() {
  clear
  echo
  TIME b "请选择执行命令编码"
  TIME y "1. 在线更新固件或转换其他作者固件"
  TIME y "2. 修改后台IP和清空密码"
  TIME y "3. 清空密码"
  TIME y "4. 重启系统"
  TIME y "5. 恢复出厂设置"
  TIME y "6. 退出程序"

  while :; do
    read -p "请输入数字： " choice
    case $choice in
      1) upgrade_firmware ;;
      2) modify_ip_and_clear_password ;;
      3) clear_password ;;
      4) reboot_system ;;
      5) restore_factory_settings ;;
      6) TIME z "您选择了退出程序" && exit 0 ;;
      *) TIME z "请输入正确的数字编号" ;;
    esac
  done
}

# 主程序入口
if [ -f '/usr/bin/AutoUpgrade' ]; then
  show_menu_with_upgrade
else
  show_menu
fi
