#!/bin/sh /etc/rc.common

START=99

start() {
    [ -f "/usr/bin/openwrt" ] && openwrt -e
    echo "$(date +%Y年%m月%d号%H时%M分%S)" >/etc/ssscrontsdsaa
}

stop() {
    # 停止操作（如果需要）
    echo "Service stopped."
}
