#!/bin/sh

chmod -R 0775 /etc/init.d /usr/share
touch /etc/crontabs/root

source /etc/openwrt_release
if [[ ! "${DISTRIB_ARCH}" == "x86_64" ]]; then
	sed -i "s?x86_64?${DISTRIB_TARGET}?g" /etc/banner
fi
if [[ "${DISTRIB_ID}" == "ImmortalWrt" ]]; then
	sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
fi

if [[ -f "/usr/lib/lua/luci/controller/ttyd.lua" ]]; then
	sed -i 's?services?system?g' "/usr/lib/lua/luci/controller/ttyd.lua"
fi

if [[ `grep -c "danshui" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/danshui/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "helloworld" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "passwall" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/passwall/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "OpenClash" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/OpenClash/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "openwrt_x" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/openwrt_x/d' /etc/opkg/distfeeds.conf
fi

if [[ `grep -c "dns_redirect" /etc/config/dhcp` -ge '1' ]]; then
	service dnsmasq stop
	sed -i '/dns_redirect/d' /etc/config/dhcp
	uci commit dhcp
	service dnsmasq start
else
	service dnsmasq stop
	uci set dhcp.@dnsmasq[0].dns_redirect='0'
	uci commit dhcp
	service dnsmasq start
fi

if [[ -f "/etc/networkdetection" ]] && [[ `grep -c "networkdetection" /etc/crontabs/root` -eq '0' ]]; then
	rm -rf /etc/networkdetection
fi

luci_web=/usr/lib/lua/luci/view/admin_status/index.htm
if [[ -f '/etc/index.htm' ]]; then
	sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "/etc/index.htm"
else
	sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "${luci_web}"
fi
if [[ -f '/etc/index.htm' ]] && [[ `grep -c "(<%=pcdata(ver.luciversion)%>)" "/etc/index.htm"` -eq '1' ]]; then
	sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "/etc/index.htm"
elif [[ `grep -c "(<%=pcdata(ver.luciversion)%>)" "${luci_web}"` -eq '1' ]]; then
	sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "${luci_web}"
fi

sed -i 's?=== WARNING! =====================================?=================== WARNING! ====================?g' /etc/profile

lmo_file="$({ find "/usr/lib/lua/luci/i18n" |grep "zh_Hans.lmo"; } 2>"/dev/null")"
for b in ${lmo_file}
do
	lmo_new_file="$(echo -e "$b"|sed "s/zh_Hans/zh-cn/g")"
	[[ -f "$b" ]] && mv "$b" "${lmo_new_file}" 2>"/dev/null"
done

if [[ -n "$(grep "downloads.openwrt.org" /etc/opkg/distfeeds.conf)" ]]; then
	sed -i 's?downloads.openwrt.org?mirrors.cloud.tencent.com/openwrt?g' /etc/opkg/distfeeds.conf
fi

if [[ -f "/usr/lib/os-release" ]]; then
	sed -i 's?RELEASE=".*"?RELEASE="Customized_Information @ OpenWrt"?g' /usr/lib/os-release
fi
if [[ -f "/usr/share/ucode/luci/version.uc" ]]; then
	sed -i '/export const revision/d' "/usr/share/ucode/luci/version.uc"
	echo "export const revision = 'SOURCE - LUCI_EDITION', branch = '';" >> "/usr/share/ucode/luci/version.uc"
fi
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Customized_Information @ OpenWrt '" >> /etc/openwrt_release
sed -i '/DISTRIB_SOURCECODE/d' /etc/openwrt_release
echo "DISTRIB_SOURCECODE='SOURCE_LUCI_EDITION'" >> /etc/openwrt_release
sed -i '/luciversion/d' /usr/lib/lua/luci/version.lua
echo "luciversion    = \"LUCI_EDITION\"" >> /usr/lib/lua/luci/version.lua
sed -i '/luciname/d' /usr/lib/lua/luci/version.lua
echo "luciname    = \"SOURCE\"" >> /usr/lib/lua/luci/version.lua
