#!/bin/sh

chmod -R 0775 /etc/init.d /usr/share
touch /etc/crontabs/root

ARCHIB="$(grep 'DISTRIB_ARCH' /etc/openwrt_release|cut -d= -f2|tr -d "'")"
DISTRIBID="$(grep 'DISTRIB_ID' /etc/openwrt_release|cut -d= -f2|tr -d "'")"
grep -q "danshui" /etc/banner && sed -i "s?x86_64?${ARCHIB}?g" /etc/banner
[[ "${DISTRIBID}" == "ImmortalWrt" ]] && sed -i "s?ImmortalWrt?OpenWrt?g" /etc/banner
[[ -f "/usr/lib/lua/luci/controller/ttyd.lua" ]] && sed -i 's?services?system?g' "/usr/lib/lua/luci/controller/ttyd.lua"
grep -q "danshui" /etc/opkg/distfeeds.conf && sed -i '/danshui/d' /etc/opkg/distfeeds.conf
grep -q "helloworld" /etc/opkg/distfeeds.conf && sed -i '/danshui/d' /etc/opkg/distfeeds.conf
grep -q "passwall" /etc/opkg/distfeeds.conf && sed -i '/danshui/d' /etc/opkg/distfeeds.conf
grep -q "OpenClash" /etc/opkg/distfeeds.conf && sed -i '/danshui/d' /etc/opkg/distfeeds.conf
grep -q "openwrt_x" /etc/opkg/distfeeds.conf && sed -i '/danshui/d' /etc/opkg/distfeeds.conf

if [[ -f "/etc/networkdetection" ]] && [[ `grep -c "networkdetection" /etc/crontabs/root` -eq '0' ]]; then
	rm -rf /etc/networkdetection
fi

luci_web=/usr/lib/lua/luci/view/admin_status/index.htm
if [[ -f '/etc/index.htm' ]]; then
	sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "/etc/index.htm"
else
	sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "${luci_web}"
fi
if [[ -f '/etc/index.htm' ]] && [[ `grep -c "(<%=pcdata(ver.luciversion)%>)" "/etc/index.htm"` -eq '1' ]]; then
	sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "/etc/index.htm"
elif [[ `grep -c "(<%=pcdata(ver.luciversion)%>)" "${luci_web}"` -eq '1' ]]; then
	sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "${luci_web}"
fi

sed -i 's?=== WARNING! =====================================?=================== WARNING! ====================?g' /etc/profile

lmo_file="$({ find "/usr/lib/lua/luci/i18n" |grep "zh_Hans.lmo"; } 2>"/dev/null")"
for b in ${lmo_file}
do
	lmo_new_file="$(echo -e "$b"|sed "s/zh_Hans/zh-cn/g")"
	[[ -f "$b" ]] && mv "$b" "${lmo_new_file}" 2>"/dev/null"
done

if [[ -f "/usr/lib/os-release" ]]; then
	sed -i 's?RELEASE=".*"?RELEASE="Customized_Information @ OpenWrt"?g' /usr/lib/os-release
fi

if [[ -f "/usr/share/ucode/luci/version.uc" ]]; then
	sed -i '/export const revision/d' "/usr/share/ucode/luci/version.uc"
	echo "export const revision = 'SOURCE - LUCI_EDITION', branch = '';" >> "/usr/share/ucode/luci/version.uc"
fi

sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Customized_Information @ OpenWrt '" >> /etc/openwrt_release
sed -i '/DISTRIB_SOURCECODE/d' /etc/openwrt_release
echo "DISTRIB_SOURCECODE='SOURCE_LUCI_EDITION'" >> /etc/openwrt_release
sed -i '/luciversion/d' /usr/lib/lua/luci/version.lua
echo "luciversion    = \"LUCI_EDITION\"" >> /usr/lib/lua/luci/version.lua
sed -i '/luciname/d' /usr/lib/lua/luci/version.lua
echo "luciname    = \"SOURCE\"" >> /usr/lib/lua/luci/version.lua

opkg_mirror="https://mirrors.vsean.net/openwrt"
distfeedlist="/etc/apk/repositories.d/distfeeds.list"
if [[ -f "${distfeedlist}" ]]; then
	sed -i.bak "s,https://downloads.openwrt.org,$opkg_mirror,g" "$distfeedlist"
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
elif grep -q "19.07" /etc/opkg/distfeeds.conf && grep -q "openwrt.org" /etc/opkg/distfeeds.conf; then
	sed -i.bak "s|https://downloads.openwrt.org/releases/.*\/|https://mirrors.ustc.edu.cn/openwrt/releases/19.07.9/|g" /etc/opkg/distfeeds.conf
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
elif grep -q "openwrt.org" /etc/opkg/distfeeds.conf; then
	sed -i.bak "s,https://downloads.openwrt.org,$opkg_mirror,g" /etc/opkg/distfeeds.conf
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
fi

if grep -q "dns_redirect" /etc/config/dhcp; then
	service dnsmasq stop
	sed -i '/dns_redirect/d' /etc/config/dhcp
	uci commit dhcp
	service dnsmasq start
else
	service dnsmasq stop
	uci set dhcp.@dnsmasq[0].dns_redirect='0'
	uci commit dhcp
	service dnsmasq start
fi




