#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=99

run_zzz_default() {
    
	if [ -f "/etc/default-setting" ]; then
		/etc/default-setting
                rm -rf /etc/default-setting
	fi
	
	openwrt -r
	
	if [ -f "/usr/bin/openwrt" ]; then
		openwrt -e
	fi
}

start() {
	run_zzz_default
}
