#
# 同步上游仓库或者清理发布都需要用REPO_TOKEN密匙
#
# 记住，同步上游是不会同步您任何自建文件夹的，所以同步后您要自己对比我现有的文件夹里面diy-part.sh和settings.ini文件有没有更新
#
# REPO_TOKEN密匙制作教程：https://git.io/jm.md
#


name: 同步
on:
  repository_dispatch:
  workflow_dispatch:
  
  schedule:
   - cron: 40 3 1 * *

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: Ubuntu-22.04
    name: 同步上游仓库
    
    steps:
    - name: 准备结束
      uses: actions/checkout@v2
      
    - name: 部署环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y git subversion git-core wget curl grep
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
          
    - name: 整理数据
      if: env.REPO_TOKEN
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/${{github.repository}}.git repogx
        git clone --depth 1 https://github.com/openwrt/packages -b master golang-version
        if [[ -d "golang-version/lang/golang" ]]; then
          rm -rf repogx/Share/golang
          cp -Rf golang-version/lang/golang repogx/Share/golang
          rm -rf golang-version
        fi
        
    - name: 同步上游仓库
      continue-on-error: true
      if: env.REPO_TOKEN
      run: |
        cd $GITHUB_WORKSPACE
        chmod -R 775 repogx
        cd repogx
        git add .
        git commit -m "up"
        git push --quiet "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
