
name: Upload
on:
  repository_dispatch:
  workflow_dispatch:
  
  schedule:
   - cron: 40 3 1 * *

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: Ubuntu-22.04
    name: Upload
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y git subversion git-core wget curl grep
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
          
    - name: Organize data
      if: env.REPO_TOKEN
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/${{github.repository}}.git repogx
        git clone --depth 1 https://github.com/openwrt/packages -b master golang-version
        if [[ -d "golang-version/lang/golang" ]]; then
          rm -rf repogx/Share/golang
          cp -Rf golang-version/lang/golang repogx/Share/golang
          rm -rf golang-version
        fi
        
        git clone https://github.com/coolsnowwolf/lede Lede
        git clone https://github.com/coolsnowwolf/openwrt-gl-ax1800 ax1800
        git clone https://github.com/Lienol/openwrt Lienol
        git clone https://github.com/immortalwrt/immortalwrt Immortalwrt
        git clone https://github.com/openwrt/openwrt Official
        git clone https://github.com/x-wrt/x-wrt Xwrt
        
        cd $GITHUB_WORKSPACE/Lede
        git branch -r |sed '/origin\/HEAD/d' |sed 's/master/18.06/g' |sed 's/$/-Lede\"/' |sed 's/origin\//=\"/g' |sed 's/openwrt-//g' >$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE/ax1800
        git branch -r |sed '/origin\/HEAD/d' |sed 's/master/gl-ax1800/g' |sed 's/$/-Lede\"/' |sed 's/origin\//=\"/g' |sed 's/openwrt-//g' >>$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE/Lienol
        git branch -r |sed '/origin\/HEAD/d' |sed 's/$/-Lienol\"/' |sed 's/origin\//=\"/g' |sed 's/openwrt-//g' >>$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE/Immortalwrt
        git branch -r |sed '/origin\/HEAD/d' |sed 's/$/-Immortalwrt\"/' |sed 's/origin\//=\"/g' |sed 's/openwrt-//g' >>$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE/Official
        git branch -r |sed '/origin\/HEAD/d' |sed 's/$/-Official\"/' |sed 's/origin\//=\"/g' |sed 's/openwrt-//g' >>$GITHUB_WORKSPACE/123
        cd $GITHUB_WORKSPACE/Xwrt
        git branch -r |sed '/origin\/HEAD/d' |sed 's/$/-Xwrt\"/' |sed 's/origin\//=\"/g' |sed 's/openwrt-//g' >>$GITHUB_WORKSPACE/123
        cd ..
        cat $GITHUB_WORKSPACE/123 |sed '/^$/d' |awk '$0=NR$0' |sed 's/^/R/' |sed s/[[:space:]]//g >$GITHUB_WORKSPACE/repogx/autoupdate/replace
        
    - name: Upload
      continue-on-error: true
      if: env.REPO_TOKEN
      run: |
        cd $GITHUB_WORKSPACE
        chmod -R 775 repogx
        cd repogx
        git add .
        git commit -m "up"
        git push --quiet "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
